<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-02T13:24:49 IST" name="Suite" finished-at="2024-08-02T13:25:13 IST" duration-ms="23386">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.LoginErrorValidation()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" name="LoginErrorValidation" class="automationFramework.Tests.ErrorValidationTest"/>
        <method signature="ErrorValidationTest.ProductErrorValidation()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" name="ProductErrorValidation" class="automationFramework.Tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" name="SubmitOrder" class="automationFramework.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-08-02T13:24:49 IST" name="Error validation Test" finished-at="2024-08-02T13:25:04 IST" duration-ms="14592">
      <class name="automationFramework.Tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:24:49 IST" name="launchApplication" finished-at="2024-08-02T13:24:54 IST" duration-ms="4425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:24:54 IST" name="LoginErrorValidation" finished-at="2024-08-02T13:24:55 IST" duration-ms="877" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at automationFramework.Tests.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:24:55 IST" name="tearDown" finished-at="2024-08-02T13:24:55 IST" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:24:55 IST" name="launchApplication" finished-at="2024-08-02T13:24:56 IST" duration-ms="1658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:24:56 IST" name="LoginErrorValidation" finished-at="2024-08-02T13:24:57 IST" duration-ms="513" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at automationFramework.Tests.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:24:57 IST" name="tearDown" finished-at="2024-08-02T13:24:57 IST" duration-ms="180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:24:57 IST" name="launchApplication" finished-at="2024-08-02T13:24:59 IST" duration-ms="2287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:24:59 IST" name="ProductErrorValidation" finished-at="2024-08-02T13:25:04 IST" duration-ms="4188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationFramework.Tests.ErrorValidationTest@25be7b63]" started-at="2024-08-02T13:25:04 IST" name="tearDown" finished-at="2024-08-02T13:25:04 IST" duration-ms="235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automationFramework.Tests.ErrorValidationTest -->
    </test> <!-- Error validation Test -->
    <test started-at="2024-08-02T13:24:49 IST" name="Submit Order Test" finished-at="2024-08-02T13:25:13 IST" duration-ms="23386">
      <class name="automationFramework.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:24:50 IST" name="launchApplication" finished-at="2024-08-02T13:24:53 IST" duration-ms="3167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:24:53 IST" name="SubmitOrder" data-provider="getData" finished-at="2024-08-02T13:24:58 IST" duration-ms="5556" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@1234, product=ZARA COAT 3, email=TestRahulShettyAcademy@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:24:58 IST" name="tearDown" finished-at="2024-08-02T13:24:58 IST" duration-ms="145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:24:58 IST" name="launchApplication" finished-at="2024-08-02T13:25:01 IST" duration-ms="2258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:25:01 IST" name="SubmitOrder" data-provider="getData" finished-at="2024-08-02T13:25:05 IST" duration-ms="4855" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@1234, product=ADIDAS ORIGINAL, email=TestRahulShettyAcademy1@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:25:05 IST" name="tearDown" finished-at="2024-08-02T13:25:06 IST" duration-ms="106" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:25:06 IST" name="launchApplication" finished-at="2024-08-02T13:25:07 IST" duration-ms="1182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:25:07 IST" name="OrderHistoryTest" finished-at="2024-08-02T13:25:12 IST" depends-on-methods="automationFramework.Tests.SubmitOrderTest.SubmitOrder" duration-ms="5658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automationFramework.Tests.SubmitOrderTest@2af004b]" started-at="2024-08-02T13:25:12 IST" name="tearDown" finished-at="2024-08-02T13:25:13 IST" duration-ms="105" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automationFramework.Tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
